name = "kotlin-releases-bot"
main = "build/index.js"
compatibility_date = "2026-09-05"

[build]
command = "cargo install -q worker-build && worker-build --release"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "SEEN"
id = "68ecab8aca0b4090a3a2e609ca690411"
